### ISSUE TITLE
Add Watchlist Tab

### ISSUE THREAD

**Issue by FerdiS-DivGro** [Portfolio-Insight/dividend-radar#12]
_I love capitalism_
Comments149 | + Follow
@FerdiS: Could you include a watchlist like the one in the CCC List, please?
19 May 2020, 10:10 AMReply

**Comment by jimmarino** [comment]
This can be done by the user. 

The recommended approach is to create a separate watch list spreadsheet and link it to DR; otherwise, the user has to manually cut-and-paste the watch list every release.
