### ISSUE TITLE
Add 5-year average yield and us it as a yield-based FV indicator

### ISSUE THREAD

**Issue by FerdiS-DivGro** [Portfolio-Insight/dividend-radar#15]
LIBERTOFINANCIERO
Comments1 | + Follow
[...] 
My suggestion is to add the 5 year yield average and maybe estimate a FV using it, as you explain here https://seekingalpha.com/article/4241695-using-average-dividend-yield-for-dividend-growth-stock-valuation
[...]
NEW|20 May 2020, 02:02 AM

**Comment by jimmarino** [comment]
We added the 5-year yield. FV is based on P/E. Yield-based based FV will be supported by dividend channels, which may be shown periodically in spotlights.
