### ISSUE TITLE
Add FV Categories

### ISSUE THREAD

**Issue by FerdiS-DivGro** [Portfolio-Insight/dividend-radar#23]
_tgro_
[...]
- Fair value estimate: indeed more categories would help 0-5% discount, 5-10, 10-20% etc.
[...]
18 May 2020, 02:05 PM

**Comment by FerdiS-DivGro** [comment]
_Ron1634_
Comments85 | + Follow
Fair value at 0-5% discount, 5-10, 10-20% etc - Yes, that would be nice [...]

**Comment by jimmarino** [comment]
Implemented
