### ISSUE TITLE
Add a Data Dictionary Tab

### ISSUE THREAD

**Issue by FerdiS-DivGro** [Portfolio-Insight/dividend-radar#25]
_13116802_
Comments166 | + Follow
As you put more info in the spreadsheet, I think it would be nice to have the Data Dictionary on its own sheet for quick easy access. Rather than online only.
Thanks (edited)
20 May 2020, 05:45 PM

**Comment by FerdiS-DivGro** [comment]
_Kiisu_ Buraun
Comments3669 | + Follow
[...]
From my perspective ... adding the data dictionary to the spreadsheet makes sense.
Why?
Assume your new CCC project is wildly popular and you provide data for many years.
Over time, the type of data[1] will (by necessity) change[2].
If the data dictionary is _not_ embedded in the spreadsheet, you should (in my opinion) provide an online date-stamped archive of data dictionaries[3] ... and (based on my experience) that complicates things for both you and your audience.
Best wishes,
Kiisu
1. And the details the user needs to properly interpret what you provide.
2. Change is what happens to long-lived projects. For example, compare David Fish's first CCC (Dec '07) with his CCCs available several years later.
3. Based on my experience as both a data maintainer and a data user.
For example, so ten years from now (after numerous data and format changes), the 7 May 2020 spreadsheet data can be interpreted as you intended it to be on 7 May 2020.
22 May 2020, 02:08 PM

**Comment by jimmarino** [comment]
This has been implemented as a separate download
